const menuPosition = [
  {
    type: "Пицца",
    name: "Буритто",
    photo: "./img_product/ветчина грибы-2.jpg",
    base: "томатная основа",
    ingredients:
      "Моцарелла, курочка, томатный соус, болгарский перец, лук, кукуруза, зелень, лёгкая пикантность",
    diameter: "30 см",
    weight: 600,
    price: 550,
    ID: "b3e0508c-070e-4120-8aa0-dc385fddc54e",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Ветчина и грибы",
    photo: "./img_product/ветчина грибы777.jpg",
    base: "томатная основа",
    ingredients: "Томатная основа, моцарелла, ветчина, грибы, зелень",
    diameter: "30 см",
    weight: 600,
    price: 500,
    ID: "ab827436-2162-453f-b3d0-dd15b1a48c99",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Гавайская",
    photo: "./img_product/ветчина грибы777.jpg",
    base: "томатная основа",
    ingredients: "Соус фирменный, моцарелла, курица, ананас, пармезан",
    diameter: "30 см",
    weight: 600,
    price: 500,
    ID: "cbffdd2f-ab26-4c14-873f-4ca97e5722e1",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Грибная",
    photo: "./img_product/ветчина грибы777.jpg",
    base: "томатная основа",
    ingredients:
      "Шампиньоны, томатный соус (бешамель на выбор), моцарелла, соус унаги, пармезан, руккола",
    diameter: "30 см",
    weight: 600,
    price: 500,
    ID: "9bd2adff-3d6f-440c-9991-3591cc39fa8d",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Друзья Ариель",
    photo: "./img_product/example.jpg",
    base: "сливочная основа",
    ingredients:
      "Соус бешамель, моцарелла, тигровые креветки, мидии, гребешок, руккола, парmезан",
    diameter: "30 см",
    weight: 600,
    price: 800,
    ID: "aafabc9d-ddb3-4d9c-b95b-822d0774d6db",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Дьябло",
    photo: "./img_product/example.jpg",
    base: "томатная основа",
    ingredients:
      "Томатный соус, моцарелла, говядина, бекон, перец болгарский, лук",
    diameter: "30 см",
    weight: 600,
    price: 600,
    ID: "88e3933a-c91d-44cc-95b6-99f451724217",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Креветки",
    photo: "./img_product/example.jpg",
    base: "томатная основа",
    ingredients:
      "Моцарелла, томатный соус, тигровые креветки, томаты, салат, пармезан",
    diameter: "30 см",
    weight: 600,
    price: 650,
    ID: "92848fc1-baa3-4965-9444-57da59e88d62",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Курица-грибы",
    photo: "./img_product/example.jpg",
    base: "томатная основа",
    ingredients: "Томатная основа, моцарелла, грибы, курочка, зелень",
    diameter: "30 см",
    weight: 600,
    price: 500,
    ID: "960f8754-454c-4873-9b62-02e2591d4a2e",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Марго",
    photo: "./img_product/example.jpg",
    base: "томатная основа",
    ingredients: "Томатная основа, моцарелла, томаты, зелень",
    diameter: "30 см",
    weight: 600,
    price: 450,
    ID: "42a38cc0-3f29-4bd4-8318-49625a658663",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Мидийность",
    photo: "./img_product/example.jpg",
    base: "сливочная основа",
    ingredients:
      "Соус бешамель, моцарелла, чеснок, соус унаги, мидии, вяленный томат, руккола, пармезан",
    diameter: "30 см",
    weight: 600,
    price: 600,
    ID: "c4eb7396-c242-4eb9-9972-f5feab86db38",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Охотничья",
    photo: "./img_product/example.jpg",
    base: "томатная основа",
    ingredients:
      "Томатная основа, моцарелла, колбаски, корнишоны, перец сладкий, лук",
    diameter: "30 см",
    weight: 600,
    price: 500,
    ID: "a646c5cc-420a-4118-a15e-943e66b08895",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Пепперони",
    photo: "./img_product/example.jpg",
    base: "томатная основа",
    ingredients: "Томатная основа, моцарелла, томат, пепперони, зелень",
    diameter: "30 см",
    weight: 600,
    price: 500,
    ID: "462b0d94-0fdf-4a69-886e-a832fe55e7f2",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Солянка",
    photo: "./img_product/example.jpg",
    base: "томатная основа",
    ingredients:
      "Томатная основа, моцарелла, бекон, курочка с/к, охотничья колбаска, перец болгарский, каперсы, маслины, чеснок, зелень",
    diameter: "30 см",
    weight: 600,
    price: 600,
    ID: "903fe182-17a8-4d8e-bbe8-ce3acb8e0aeb",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Сырная груша",
    photo: "./img_product/example.jpg",
    base: "сливочная основа",
    ingredients: "Соус бешамель, груша, Блю-чиз, моцарелла, миндаль, пармезан",
    diameter: "30 см",
    weight: 600,
    price: 600,
    ID: "4896acc7-2208-4b78-9fa9-b12395e25e7e",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Сёмга",
    photo: "./img_product/example.jpg",
    base: "сливочная основа",
    ingredients: "Соус бешамель, моцарелла, сёмга, руккола, пармезан",
    diameter: "30 см",
    weight: 600,
    price: 750,
    ID: "0770c19a-f64d-4c4e-9c0a-192bb84c249f",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Том Ям",
    photo: "./img_product/example.jpg",
    base: "Паста Том Ям",
    ingredients:
      "Острый соус Том Ям (бешамель на выбор) бекон, пармезан, моцарелла, зелень",
    diameter: "30 см",
    weight: 600,
    price: 550,
    ID: "643f82e4-3d9f-4b5a-bdfc-cf11db705d84",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Цезарь-креветки",
    photo: "./img_product/example.jpg",
    base: "сливочная основа",
    ingredients: "Соус цезарь, моцарелла, черри, креветки, ромейн, пармезан",
    diameter: "30 см",
    weight: 600,
    price: 700,
    ID: "0f61615e-28d5-4527-8123-19d62c05dd0b",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Цезарь-курица",
    photo: "./img_product/example.jpg",
    base: "сливочная основа",
    ingredients: "Соус цезарь, моцарелла, черри, курочка, ромейн, пармезан",
    diameter: "30 см",
    weight: 600,
    price: 600,
    ID: "346082b4-e5af-4d91-8ca4-8097cf1b340c",
    extra: [],
  },
  {
    type: "Пицца",
    name: "Четыре сыра",
    photo: "./img_product/example.jpg",
    base: "сливочная основа",
    ingredients: "Соус бешамель, моцарелла, чеддар, блю чиз, пармезан",
    diameter: "30 см",
    weight: 600,
    price: 600,
    ID: "b031f7d2-bcfc-408e-ac28-d3311dbcc2f7",
    extra: [],
  },
];

window.menuPosition = menuPosition;

const extraItems = [
  {
    name: "Моцарелла",
    price: 79,
  },
  {
    name: "Блю Чиз",
    price: 79,
  },
  {
    name: "Пармезан",
    price: 79,
  },
  {
    name: "Чеддер",
    price: 79,
  },
  {
    name: "Острый халапеньо",
    price: 59,
  },
  {
    name: "Нежный цыпленок",
    price: 79,
  },
  {
    name: "Говядина",
    price: 79,
  },
  {
    name: "Сочный бекон",
    price: 79,
  },
  {
    name: "Ветчина",
    price: 79,
  },
  {
    name: "Колбаска Пепперони",
    price: 79,
  },
  {
    name: "Грибы жареные",
    price: 59,
  },
  {
    name: "Соленый огурчик",
    price: 59,
  },
  {
    name: "Маслины/оливки",
    price: 59,
  },
];

window.extraItems = extraItems;
